# Generated by Django 3.2.8 on 2021-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужской'), ('woman', 'Женский')], max_length=8, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(upload_to='user_pictures', verbose_name='Загрузить фото'),
        ),
    ]
