# Generated by Django 3.2.8 on 2021-10-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211016_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(null=True, upload_to='user_pictures', verbose_name='Загрузить фото'),
        ),
    ]
