# Generated by Django 3.2.8 on 2021-10-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures', verbose_name='Загрузить фото'),
        ),
    ]
