# Generated by Django 3.2.8 on 2021-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211017_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lng',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.DeleteModel(
            name='UserCoords',
        ),
    ]
